- name: Creathe config
  docker_volume:
    name: nzbget_config
    driver: local
    driver_options:
      type: nfs
      device: :/mnt/ocean/block_storage/nzbget-config
      o: addr=192.168.1.81,rw,vers=4,async

- name: create downloads folder
  docker_volume:
    name: nzbget_downloads
    driver: local
    driver_options:
      type: nfs
      device: :/mnt/ocean/downloads/usenet
      o: addr=192.168.1.81,rw,vers=4,async

- name: Nzbget
  docker_container:
    name: nzbget
    state: started
    image: linuxserver/nzbget
    restart_policy: always
    memory: "64M"
    cpu_shares: 512
    env:
      PUID: "0"
      PGID: "0"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.nzbget.rule: Host(`nzbget.wg`)
      traefik.http.routers.nzbget.entrypoints: web
    volumes:
      - nzbget_config:/config:nocopy
      - nzbget_downloads:/data/downloads/usenet:nocopy
    networks:
      - name: proxy
      - name: media
