- name: Create Traefik container
  docker_container:
    name: traefik
    state: started
    image: traefik:2.2.1
    recreate: true
    restart_policy: always
    memory: "34M"
    cpu_shares: 1024
    ports:
     - "{{ wg_ip }}:80:80"
     - "{{ wg_ip }}:443:443"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
#        --log.level=DEBUG
    hostname: traefik
    command: >
      --api.insecure=true
      --metrics.prometheus=true
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.wg`)  || Host(`traefik`)"
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
    networks:
      - name: prom

# sudo docker exec -it graf grafana-cli plugins install grafana-piechart-panel
